# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manager',
            table='empts_manager',
        ),
    ]
