# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empts', '0002_auto_20160312_1357'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manager',
            table=None,
        ),
    ]
