# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import empts.models


class Migration(migrations.Migration):

    dependencies = [
        ('empts', '0003_auto_20160312_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=120)),
                ('battery', models.IntegerField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('current_location', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'empts_device',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=empts.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=30)),
                ('phone_model', models.CharField(max_length=120)),
                ('imei', models.IntegerField(max_length=17)),
            ],
            options={
                'db_table': 'empts_employee',
            },
        ),
        migrations.RemoveField(
            model_name='manager',
            name='id',
        ),
        migrations.AddField(
            model_name='manager',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=empts.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='manager',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='manager',
            table='empts_manager',
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empts.Employee'),
        ),
        migrations.AddField(
            model_name='manager',
            name='emp',
            field=models.ForeignKey(default=datetime.datetime(2016, 3, 15, 19, 24, 21, 862543, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='empts.Employee'),
            preserve_default=False,
        ),
    ]
