# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empts', '0004_auto_20160316_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='battery',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='imei',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
