# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empts', '0005_auto_20160316_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='emp',
        ),
        migrations.AddField(
            model_name='employee',
            name='managed_by',
            field=models.ForeignKey(default=datetime.datetime(2016, 3, 15, 19, 33, 33, 579162, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='empts.Manager'),
            preserve_default=False,
        ),
    ]
